<?php
namespace VanguardLTE\Services;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use VanguardLTE\{StockAsset, StockPosition, StockPriceSnapshot, StockRound, User};

/** Server-authoritative stock simulator. Yahoo is read only by the signed Hub; each round keeps its own evidence. */
class StockTradingService
{
    public const INTERVALS = ['hourly','daily','weekly']; private const GRACE = 120; private const MAX_PROFIT = 100.0;
    public function refreshCatalog(): array {
        try { $lock=DB::selectOne('SELECT GET_LOCK(?, 0) AS acquired',['stock-trading:catalog-refresh']); if ((int)($lock->acquired??0)!==1) return ['success'=>false,'message'=>'The stock market cache is already being refreshed.']; } catch (\Throwable) { return ['success'=>false,'message'=>'The stock market refresh lock is unavailable.']; }
        try {
            $feed=app(StockPriceService::class)->markets(); if (($feed['success']??false)!==true) return $feed; if (($feed['stale']??false)===true) return ['success'=>false,'message'=>'The stock cache is stale; no round price will be captured from it.'];
            $first=StockAsset::count()===0; $now=now('UTC'); $order=0;
            foreach ((array)($feed['stocks']??[]) as $stock) { $order++; if (!is_array($stock)||!is_string($stock['id']??null)||!is_numeric($stock['price_usd']??null)) continue; $values=['symbol'=>strtoupper((string)($stock['symbol']??'')),'name'=>(string)($stock['name']??$stock['id']),'exchange'=>(string)($stock['exchange']??''),'price_usd'=>round((float)$stock['price_usd'],6),'change_percent'=>isset($stock['change_percent'])&&is_numeric($stock['change_percent'])?(float)$stock['change_percent']:null,'provider_updated_at'=>$this->providerTime($stock['market_time']??null),'updated_at'=>$now]; $asset=StockAsset::where('provider_id',$stock['id'])->first(); if (!$asset) { $values['provider_id']=$stock['id']; $values['is_enabled']=$first&&$order<=20; $values['created_at']=$now; StockAsset::insert($values); } else $asset->fill($values)->save(); }
            return ['success'=>true,'count'=>StockAsset::count(),'enabled'=>StockAsset::where('is_enabled',true)->count(),'feed'=>$feed];
        } finally { try { DB::selectOne('SELECT RELEASE_LOCK(?) AS released',['stock-trading:catalog-refresh']); } catch (\Throwable) {} }
    }
    public function processDueRounds(): array {
        $refresh=$this->refreshCatalog(); $now=now('UTC'); $opened=$settled=$voided=0;
        foreach (StockRound::with('asset')->where('status','scheduled')->where('starts_at','<=',$now)->orderBy('starts_at')->get() as $round) { if (($refresh['success']??false)===true&&$this->capture($round,'open',$now)) $opened++; elseif ($round->starts_at->copy()->addSeconds(self::GRACE)->lte($now)) { $this->voidRound($round,'Opening price was unavailable.'); $voided++; } }
        foreach (StockRound::with('asset')->where('status','open')->where('ends_at','<=',$now)->orderBy('ends_at')->get() as $round) { if (($refresh['success']??false)===true&&$this->capture($round,'close',$now)) { $this->settleRound($round); $settled++; } elseif ($round->ends_at->copy()->addSeconds(self::GRACE)->lte($now)) { $this->voidRound($round,'Closing price was unavailable.'); $voided++; } }
        return compact('refresh','opened','settled','voided');
    }
    public function queuePosition(User $user,int $assetId,string $requested,string $direction,float $stake,float $leverage): StockPosition {
        if (!in_array($requested,array_merge(self::INTERVALS,['manual']),true)||!in_array($direction,['long','short'],true)||$stake<1||$stake>1000000||!in_array($leverage,[1.0,2.0,3.0],true)) throw new \RuntimeException('Choose a valid stock position, interval, cost, and leverage.');
        return DB::transaction(function() use($user,$assetId,$requested,$direction,$stake,$leverage) { $asset=StockAsset::whereKey($assetId)->where('is_enabled',true)->lockForUpdate()->first(); if (!$asset) throw new \RuntimeException('This stock is not available for new positions.'); $interval=$requested==='manual'?'hourly':$requested; $round=$this->roundFor($asset,$interval,now('UTC')); $dbUser=DB::table('users')->where('id',$user->id)->lockForUpdate()->first(); if (!$dbUser||(float)$dbUser->balance<$stake) throw new \RuntimeException('Insufficient Cedar Coins balance.'); $before=(float)$dbUser->balance; $after=round($before-$stake,2); DB::table('users')->where('id',$user->id)->update(['balance'=>$after,'updated_at'=>now()]); $position=StockPosition::create(['user_id'=>$user->id,'stock_asset_id'=>$asset->id,'stock_round_id'=>$round->id,'requested_interval'=>$requested,'direction'=>$direction,'leverage'=>$leverage,'stake'=>$stake,'status'=>'queued']); $this->transaction($user->id,'deduct',$stake,$before,$after,'stock_position_stake',"Stock {$direction} {$asset->symbol} {$round->round_code} (Position #{$position->id})"); $user->balance=$after; return $position->load(['asset','round']); });
    }
    public function nextBatchStart(string $interval,?Carbon $from=null): Carbon { $from=($from?:now('UTC'))->copy()->utc(); if ($interval==='manual'||$interval==='hourly') return $from->copy()->startOfHour()->addHour(); if ($interval==='daily') return $from->copy()->startOfDay()->addDay(); return $from->copy()->startOfWeek(Carbon::MONDAY)->addWeek(); }
    private function roundFor(StockAsset $asset,string $interval,Carbon $from): StockRound { $start=$this->nextBatchStart($interval,$from); $end=match($interval){'hourly'=>$start->copy()->addHour(),'daily'=>$start->copy()->addDay(),'weekly'=>$start->copy()->addWeek()}; return StockRound::firstOrCreate(['stock_asset_id'=>$asset->id,'interval'=>$interval,'starts_at'=>$start],['round_code'=>strtoupper($asset->symbol).'-'.strtoupper($interval).'-'.$start->format('YmdHi').'Z','ends_at'=>$end,'status'=>'scheduled']); }
    private function capture(StockRound $round,string $checkpoint,Carbon $now): bool { return DB::transaction(function() use($round,$checkpoint,$now) { $locked=StockRound::with('asset')->whereKey($round->id)->lockForUpdate()->first(); if (!$locked||($checkpoint==='open'&&$locked->status!=='scheduled')||($checkpoint==='close'&&$locked->status!=='open')) return false; $asset=$locked->asset; if (!$asset||!is_numeric($asset->price_usd)||(float)$asset->price_usd<=0) return false; $item=['id'=>$asset->provider_id,'symbol'=>$asset->symbol,'price_usd'=>(float)$asset->price_usd,'updated_at'=>optional($asset->provider_updated_at)->toIso8601String()]; $payload=json_encode($item,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR); StockPriceSnapshot::firstOrCreate(['stock_round_id'=>$locked->id,'checkpoint'=>$checkpoint],['stock_asset_id'=>$asset->id,'price_usd'=>$asset->price_usd,'observed_at'=>$now,'provider_updated_at'=>$asset->provider_updated_at,'payload_hash'=>hash('sha256',$payload),'provider_payload'=>$payload]); if ($checkpoint==='open') { $locked->update(['open_price_usd'=>$asset->price_usd,'status'=>'open','opened_at'=>$now]); StockPosition::where('stock_round_id',$locked->id)->where('status','queued')->update(['entry_price_usd'=>$asset->price_usd,'status'=>'open','updated_at'=>$now]); } else $locked->update(['close_price_usd'=>$asset->price_usd]); return true; }); }
    private function settleRound(StockRound $round): void { DB::transaction(function() use($round) { $round=StockRound::whereKey($round->id)->lockForUpdate()->firstOrFail(); if ($round->status!=='open'||!$round->open_price_usd||!$round->close_price_usd) return; $now=now(); foreach(StockPosition::where('stock_round_id',$round->id)->whereIn('status',['queued','open'])->lockForUpdate()->get() as $position) { $raw=$position->direction==='long'?((float)$round->close_price_usd/(float)$round->open_price_usd-1):((float)$round->open_price_usd/(float)$round->close_price_usd-1); $percent=max(-100.0,min(self::MAX_PROFIT,$raw*(float)$position->leverage*100)); $payout=round((float)$position->stake*max(0,1+$percent/100),2); $status=$payout>(float)$position->stake?'won':($payout>0?'lost_partial':'lost'); $position->update(['entry_price_usd'=>$round->open_price_usd,'exit_price_usd'=>$round->close_price_usd,'return_percent'=>$percent,'payout_amount'=>$payout,'status'=>$status,'settled_at'=>$now]); if($payout>0)$this->credit($position->user_id,$payout,'stock_position_settle',"Stock {$round->round_code} position #{$position->id}"); } $round->update(['status'=>'settled','settled_at'=>$now]); }); }
    private function voidRound(StockRound $round,string $reason): void { DB::transaction(function() use($round,$reason) { $round=StockRound::whereKey($round->id)->lockForUpdate()->firstOrFail(); if(in_array($round->status,['settled','void'],true))return; foreach(StockPosition::where('stock_round_id',$round->id)->whereIn('status',['queued','open'])->lockForUpdate()->get() as $position) { $stake=(float)$position->stake; $position->update(['payout_amount'=>$stake,'status'=>'refunded','settled_at'=>now()]); $this->credit($position->user_id,$stake,'stock_position_refund',"{$reason} Position #{$position->id}"); } $round->update(['status'=>'void','settled_at'=>now()]); }); }
    private function credit(int $userId,float $amount,string $source,string $note): void { $user=DB::table('users')->where('id',$userId)->lockForUpdate()->first(); if(!$user)return; $before=(float)$user->balance; $after=round($before+$amount,2); DB::table('users')->where('id',$userId)->update(['balance'=>$after,'count_balance'=>(float)$user->count_balance+$amount,'updated_at'=>now()]); $this->transaction($userId,'add',$amount,$before,$after,$source,$note); }
    private function transaction(int $userId,string $direction,float $amount,float $before,float $after,string $source,string $note): void { DB::table('transactions')->insert(['user_id'=>$userId,'admin_id'=>null,'direction'=>$direction,'amount'=>$amount,'balance_before'=>$before,'balance_after'=>$after,'source'=>$source,'note'=>$note,'created_at'=>now(),'updated_at'=>now()]); }
    private function providerTime(mixed $value): ?Carbon { try { return $value?Carbon::parse($value)->utc():null; } catch(\Throwable) { return null; } }
}
