@extends('liteback.layout')

@section('title', 'Kripto Ticareti')
@section('page_title', 'Kripto Ticareti Simulator')

@section('content')
<div class="row"><div class="col-12"><div class="card card-dark"><div class="card-header d-flex align-items-center justify-content-between"><div><h3 class="card-title">Lisanslı Kripto Kataloğu</h3><p class="mb-0 text-muted small">The refresh calls the signed PROMEX cache once. The first successful refresh enables the ranked top 20; toggles only affect new positions.</p></div><form method="POST" action="{{ route('liteback.crypto.refresh') }}">@csrf<button class="btn btn-info"><i class="fas fa-sync mr-1"></i> Kataloğu yenile</button></form></div><div class="card-body p-0 table-responsive"><table class="table table-striped table-sm mb-0"><thead><tr><th>Sıra</th><th>Para Birimi</th><th>Önbelleğe alınmış USD fiyatı</th><th>24h</th><th>Sağlayıcı zaman damgası</th><th>Yeni pozisyonlar</th><th></th></tr></thead><tbody>@forelse($assets as $asset)<tr><td>#{{ $asset->market_rank ?? '—' }}</td><td><strong>{{ $asset->name }}</strong> <code>{{ $asset->symbol }}</code></td><td>${{ number_format($asset->price_usd ?? 0, ($asset->price_usd ?? 0) < 1 ? 6 : 2) }}</td><td class="{{ ($asset->change_24h ?? 0) >= 0 ? 'text-success' : 'text-danger' }}">{{ number_format($asset->change_24h ?? 0, 2) }}%</td><td class="small">{{ optional($asset->provider_updated_at)->format('Y-m-d H:i:s') ?? '—' }} UTC</td><td><span class="badge badge-{{ $asset->is_enabled ? 'success' : 'secondary' }}">{{ $asset->is_enabled ? 'Enabled' : 'Disabled' }}</span></td><td><form method="POST" action="{{ route('liteback.crypto.assets.toggle', $asset) }}">@csrf<button class="btn btn-sm btn-outline-{{ $asset->is_enabled ? 'warning' : 'success' }}">{{ $asset->is_enabled ? 'Disable' : 'Enable' }}</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Önbelleğe alınmış para birimi yok. İlk 20'yi tohumlamak için lisanslı kataloğu yenileyin.</td></tr>@endforelse</tbody></table></div>@if($assets->hasPages())<div class="card-footer">{{ $assets->links() }}</div>@endif</div></div></div>
<div class="row"><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Son gruplar</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Tur</th><th>Pencere UTC</th><th>Açılış → kapanış</th><th>Durum</th></tr></thead><tbody>@forelse($rounds as $round)<tr><td>{{ $round->asset->symbol }} · {{ $round->interval }}</td><td class="small">{{ $round->starts_at->format('m-d H:i') }} → {{ $round->ends_at->format('m-d H:i') }}</td><td>${{ $round->open_price_usd ?? '—' }} → ${{ $round->close_price_usd ?? '—' }}</td><td>{{ $round->status }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">Henüz grup yok.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Son pozisyonlar</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Oyuncu</th><th>Pozisyon</th><th>Maliyet</th><th>Sonuç</th><th>Durum</th></tr></thead><tbody>@forelse($positions as $position)<tr><td>{{ $position->user->username ?? $position->user_id }}</td><td>{{ $position->asset->symbol }} {{ $position->direction }} {{ $position->leverage }}×</td><td>{{ number_format($position->stake, 2) }}</td><td>{{ $position->return_percent === null ? '—' : number_format($position->return_percent, 2).'%' }}</td><td>{{ str_replace('_', ' ', $position->status) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">Henüz pozisyon yok.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
