<?php
declare(strict_types=1);
require __DIR__ . '/../../../tools/packaging/build_patch.php';
use VanguardLTE\Services\PatchPackage;
$root = sys_get_temp_dir() . '/promex-patch-tests-' . bin2hex(random_bytes(6));
mkdir($root . '/before/public', 0700, true); mkdir($root . '/after/public', 0700, true);
$options = ['private_key_bits' => 2048]; if (getenv('OPENSSL_CONF')) $options['config'] = getenv('OPENSSL_CONF');
$key = openssl_pkey_new($options); openssl_pkey_export($key, $private, null, $options); $public = openssl_pkey_get_details($key)['key'];
$checks = 0;
$ok = function ($condition, $name) use (&$checks) { if (!$condition) throw new RuntimeException('FAIL: ' . $name); $checks++; echo 'PASS: ' . $name . PHP_EOL; };
$fails = function ($name, $work) use ($ok) { try { $work(); } catch (Throwable $e) { $ok(true, $name); return; } $ok(false, $name); };
file_put_contents($root . '/before/VERSION', '2.0.0'); file_put_contents($root . '/after/VERSION', '2.0.1');
file_put_contents($root . '/before/public/example.txt', 'old'); file_put_contents($root . '/after/public/example.txt', 'new');
$recipe = ['id' => 'patch-core-2-0-1', 'component' => 'core', 'from' => '2.0.0', 'to' => '2.0.1', 'title' => 'Fixture', 'notes' => 'Fixture', 'requires' => [], 'files' => ['VERSION', 'public/example.txt'], 'delete' => [], 'migrations' => []];
buildPromexPatch($root . '/before', $root . '/after', $recipe, $private, $root . '/valid.zip');
$m = PatchPackage::inspect($root . '/valid.zip', $public);
PatchPackage::eligibility($m, [], $root . '/before'); $ok(true, 'Signed delta accepted for matching baseline');
$state = ['versions' => ['core' => '2.0.1']];
$fails('Out-of-order version blocked', fn () => PatchPackage::eligibility($m, $state, $root . '/before'));
$fails('Duplicate patch blocked', fn () => PatchPackage::eligibility($m, ['installed' => [$m['id'] => 'hash']], $root . '/before'));
$dependency = $m; $dependency['requires'] = ['earlier'];
$fails('Missing prerequisite blocked', fn () => PatchPackage::eligibility($dependency, [], $root . '/before'));
$fails('Failed patch blocks later work', fn () => PatchPackage::eligibility($m, ['history' => [['status' => 'failed']]], $root . '/before'));
$fails('Interrupted patch blocks later work', fn () => PatchPackage::eligibility($m, ['history' => [['status' => 'installing']]], $root . '/before'));
file_put_contents($root . '/before/public/example.txt', 'operator customized');
$fails('Local modifications protected', fn () => PatchPackage::eligibility($m, [], $root . '/before'));
copy($root . '/valid.zip', $root . '/tampered.zip'); $zip = new ZipArchive(); $zip->open($root . '/tampered.zip'); $zip->addFromString('files/public/example.txt', 'tampered'); $zip->close();
$fails('Tampered payload rejected', fn () => PatchPackage::inspect($root . '/tampered.zip', $public));
copy($root . '/valid.zip', $root . '/extra.zip'); $zip->open($root . '/extra.zip'); $zip->addFromString('../escape', 'bad'); $zip->close();
$fails('Unexpected traversal ZIP entry rejected', fn () => PatchPackage::inspect($root . '/extra.zip', $public));
foreach (['../escape', 'casino/.env', 'casino/vendor/package/file.php', 'games/GameX/index.html', 'CedarGames/CedarDice/index.html', 'casino/bootstrap/cache/config.php', 'casino/app/Services/CedarLegacyGameService.php'] as $path) $ok(!PatchPackage::allowedPath($path, 'core'), 'Core excludes ' . $path);
$ok(PatchPackage::allowedPath('games/GameX/index.html', 'legacy:GameX') && !PatchPackage::allowedPath('games/GameY/index.html', 'legacy:GameX'), 'Legacy patch confined to one game');
$ok(!PatchPackage::allowedPath('games/CedarDice/index.html', 'legacy:CedarDice'), 'Cedar cannot masquerade as legacy');
$ok(!PatchPackage::allowedPath('casino/app/Example.php', 'demo'), 'Practice confined to fixture paths');
$zip->open($root . '/valid.zip'); $envelope = json_decode($zip->getFromName('patch.json'), true); $zip->close(); $envelope['signed_payload'] .= ' ';
$fails('Changed manifest signature rejected', fn () => PatchPackage::manifest($envelope, $public));
$fails('Published artifact is immutable', fn () => buildPromexPatch($root . '/before', $root . '/after', $recipe, $private, $root . '/valid.zip'));
echo "{$checks} checks passed. Isolated fixtures: {$root}\n";
