<?php

namespace VanguardLTE\Http\Controllers\Web\Liteback;

use VanguardLTE\Http\Controllers\Controller;

class HelpController extends Controller
{
    private const LANGUAGES = ['en'=>'EN','fr'=>'FR','es'=>'ES','ru'=>'RU','tr'=>'TR','ar'=>'AR','he'=>'HE'];

    public function index(?string $locale = 'en')
    {
        $locale = array_key_exists($locale, self::LANGUAGES) ? $locale : 'en';
        $guide = $this->guides()[$locale];
        $icons = ['users','gamepad','tree','trophy','credit-card','dice','magic','chart-line','chart-line','user-friends','gem','cogs','store','user-shield'];
        foreach ($guide['sections'] as $index => &$section) $section['icon'] = $icons[$index];

        return view('liteback.help.index', [
            'locale' => $locale,
            'languages' => self::LANGUAGES,
            'guide' => $guide,
            'rtl' => in_array($locale, ['ar', 'he'], true),
        ]);
    }

    private function guides(): array
    {
        return [
            'en' => ['title'=>'Liteback Help','intro'=>'A short guide to the operator console. Confirm important changes before saving: some actions affect player visibility, balances, or active services.', 'sections'=>[
                ['title'=>'Users','body'=>'Find player accounts, review their status, and make only documented balance adjustments. Use account detail before changing a user.'],
                ['title'=>'Games','body'=>'Manage the regular game catalog, visibility, provider actions, and delivery settings. Deactivate a title when you need to hide it without deleting history.'],
                ['title'=>'CEDAR','body'=>'Manage the protected CEDAR catalog separately from ordinary games. Use sync only for entitled catalog updates; keep game IDs and past rounds intact.'],
                ['title'=>'Sportsbook','body'=>'Use its dashboard, categories, events, settlements, and settings to control the sports area. Settle or refund only after reviewing the source outcome.'],
                ['title'=>'Payments & Cashouts','body'=>'Review manual deposits and withdrawal requests before approval. Gateway settings control payment connections; never enter credentials in notes or public fields.'],
                ['title'=>'Lotto Jackpot Zone','body'=>'Create or enable draw games, configure visible result columns, and run a specified draw only when its round is ready. Results are recorded for audit.'],
                ['title'=>'Prediction Markets','body'=>'Create and review markets here. Settlement is a consequential action: verify the final outcome and use the documented resolution process.'],
                ['title'=>'Crypto Trading','body'=>'Refresh the licensed cached market list and choose which assets players may use. Player positions settle using recorded snapshots, not browser prices.'],
                ['title'=>'Stock Trading','body'=>'Refresh the cached stock universe and enable or disable assets for players. Existing round evidence is preserved when availability changes.'],
                ['title'=>'Affiliates & Referrals','body'=>'Configure referral rates and review the programme. Apply rate changes carefully because they affect future reward calculations.'],
                ['title'=>'VIP Club & Rakeback','body'=>'Configure VIP settings and, where allowed, adjust a user tier. Check the player record before granting a manual tier.'],
                ['title'=>'System & API Settings','body'=>'Control feature visibility, branding, delivery providers, and operational settings. Test a provider connection before relying on it and keep at least one sign-in method enabled.'],
                ['title'=>'Store & License','body'=>'Review the license status, request supported downloads, and run approved updates. Do not replace keys or deploy updates without an authorized release plan.'],
                ['title'=>'Account Security','body'=>'Use this area for your own password and contact settings. Keep the administrator account protected and never share its credentials.'],
            ]],
            'fr' => ['title'=>'Aide Liteback','intro'=>'Guide court de la console opérateur. Confirmez les changements importants avant de sauvegarder : certaines actions affectent la visibilité, les soldes ou les services.', 'sections'=>[
                ['title'=>'Utilisateurs','body'=>'Recherchez les comptes, vérifiez leur statut et documentez tout ajustement de solde. Consultez le détail avant toute modification.'],['title'=>'Jeux','body'=>'Gérez le catalogue, la visibilité, les fournisseurs et la livraison. Désactivez un titre pour le masquer sans supprimer l’historique.'],['title'=>'CEDAR','body'=>'Gérez le catalogue CEDAR protégé séparément. Synchronisez uniquement les mises à jour autorisées et conservez les identifiants et manches passées.'],['title'=>'Paris sportifs','body'=>'Utilisez le tableau de bord, les catégories, événements, règlements et réglages. Réglez ou remboursez seulement après vérification du résultat source.'],['title'=>'Paiements et retraits','body'=>'Vérifiez les dépôts manuels et demandes de retrait avant approbation. Ne saisissez jamais de secrets dans des notes ou champs publics.'],['title'=>'Zone Jackpot Lotto','body'=>'Créez ou activez les tirages, réglez les colonnes de résultat et lancez un tirage précis uniquement lorsqu’il est prêt. Les résultats sont audités.'],['title'=>'Marchés prédictifs','body'=>'Créez et vérifiez les marchés ici. Le règlement est important : confirmez le résultat final et suivez le processus prévu.'],['title'=>'Trading crypto','body'=>'Actualisez la liste de marché sous licence et choisissez les actifs disponibles. Les positions utilisent des relevés enregistrés, pas les prix du navigateur.'],['title'=>'Trading actions','body'=>'Actualisez l’univers d’actions et activez ou désactivez les actifs. Les preuves des manches existantes sont conservées.'],['title'=>'Affiliés et parrainages','body'=>'Configurez les taux de parrainage et suivez le programme. Les changements affectent les futurs calculs de récompense.'],['title'=>'Club VIP et rakeback','body'=>'Configurez le VIP et, si autorisé, modifiez le niveau d’un joueur. Vérifiez toujours son dossier auparavant.'],['title'=>'Réglages système et API','body'=>'Contrôlez la visibilité, l’image de marque, les fournisseurs et les réglages. Testez une connexion et gardez au moins une méthode de connexion active.'],['title'=>'Boutique et licence','body'=>'Consultez la licence, demandez les téléchargements pris en charge et appliquez les mises à jour approuvées. Ne remplacez pas de clé sans autorisation.'],['title'=>'Sécurité du compte','body'=>'Gérez votre mot de passe et vos contacts. Protégez le compte administrateur et ne partagez jamais ses identifiants.'],
            ]],
            'es' => ['title'=>'Ayuda de Liteback','intro'=>'Guía breve de la consola del operador. Confirma cambios importantes antes de guardar: algunas acciones afectan la visibilidad, los saldos o los servicios.', 'sections'=>[
                ['title'=>'Usuarios','body'=>'Busca cuentas, revisa su estado y documenta cualquier ajuste de saldo. Consulta el detalle antes de modificar a un jugador.'],['title'=>'Juegos','body'=>'Gestiona catálogo, visibilidad, proveedores y entrega. Desactiva un título para ocultarlo sin borrar el historial.'],['title'=>'CEDAR','body'=>'Gestiona el catálogo protegido de CEDAR por separado. Sincroniza solo actualizaciones autorizadas y conserva IDs y rondas anteriores.'],['title'=>'Sportsbook','body'=>'Usa el panel, categorías, eventos, liquidaciones y ajustes para controlar deportes. Liquida o reembolsa solo tras verificar el resultado fuente.'],['title'=>'Pagos y retiros','body'=>'Revisa depósitos manuales y solicitudes de retiro antes de aprobar. Nunca ingreses secretos en notas ni campos públicos.'],['title'=>'Zona Jackpot Lotto','body'=>'Crea o activa sorteos, configura columnas y ejecuta un sorteo específico solo cuando esté listo. Los resultados quedan auditados.'],['title'=>'Mercados de predicción','body'=>'Crea y revisa mercados aquí. La liquidación es importante: verifica el resultado final y sigue el proceso documentado.'],['title'=>'Trading cripto','body'=>'Actualiza la lista de mercado autorizada y elige activos disponibles. Las posiciones usan capturas registradas, no precios del navegador.'],['title'=>'Trading de acciones','body'=>'Actualiza el universo de acciones y activa o desactiva activos. La evidencia de rondas existentes se conserva.'],['title'=>'Afiliados y referidos','body'=>'Configura tasas de referidos y revisa el programa. Los cambios afectan cálculos de futuras recompensas.'],['title'=>'Club VIP y rakeback','body'=>'Configura VIP y, cuando esté permitido, ajusta el nivel de un usuario. Revisa siempre el registro del jugador primero.'],['title'=>'Sistema y API','body'=>'Controla visibilidad, marca, proveedores y ajustes operativos. Prueba conexiones y mantén activo al menos un método de acceso.'],['title'=>'Tienda y licencia','body'=>'Revisa la licencia, solicita descargas admitidas y ejecuta actualizaciones aprobadas. No reemplaces claves ni despliegues sin autorización.'],['title'=>'Seguridad de cuenta','body'=>'Gestiona tu contraseña y contactos. Protege la cuenta administradora y nunca compartas sus credenciales.'],
            ]],
            'ru' => ['title'=>'Справка Liteback','intro'=>'Краткое руководство по консоли оператора. Подтверждайте важные изменения перед сохранением: некоторые действия влияют на видимость, балансы или сервисы.', 'sections'=>[
                ['title'=>'Пользователи','body'=>'Находите учётные записи, проверяйте статус и документируйте корректировки баланса. Перед изменением откройте карточку игрока.'],['title'=>'Игры','body'=>'Управляйте каталогом, видимостью, провайдерами и доставкой. Деактивируйте игру, чтобы скрыть её без удаления истории.'],['title'=>'CEDAR','body'=>'Управляйте защищённым каталогом CEDAR отдельно. Синхронизируйте только разрешённые обновления и сохраняйте ID и прошлые раунды.'],['title'=>'Спортбук','body'=>'Используйте панель, категории, события, расчёты и настройки для раздела спорта. Рассчитывайте или возвращайте ставку только после проверки исхода.'],['title'=>'Платежи и выводы','body'=>'Проверяйте ручные депозиты и заявки на вывод до одобрения. Никогда не вводите секреты в заметки или публичные поля.'],['title'=>'Лотерея и джекпот','body'=>'Создавайте или включайте тиражи, настраивайте колонки результата и запускайте конкретный тираж только когда он готов. Результаты аудируются.'],['title'=>'Рынки прогнозов','body'=>'Создавайте и проверяйте рынки здесь. Расчёт важен: подтвердите итог и следуйте документированному процессу.'],['title'=>'Криптотрейдинг','body'=>'Обновляйте лицензированный список рынка и выбирайте доступные активы. Позиции используют зафиксированные снимки, а не цены браузера.'],['title'=>'Торговля акциями','body'=>'Обновляйте список акций и включайте или отключайте активы. Доказательства существующих раундов сохраняются.'],['title'=>'Партнёры и рефералы','body'=>'Настраивайте реферальные ставки и просматривайте программу. Изменения влияют на будущие расчёты наград.'],['title'=>'VIP и рейкбек','body'=>'Настраивайте VIP и, где разрешено, меняйте уровень игрока. Всегда сначала проверяйте запись игрока.'],['title'=>'Система и API','body'=>'Управляйте видимостью, брендом, провайдерами и настройками. Проверяйте подключение и оставляйте активным хотя бы один способ входа.'],['title'=>'Магазин и лицензия','body'=>'Проверяйте лицензию, запрашивайте поддерживаемые загрузки и применяйте одобренные обновления. Не меняйте ключи и не развёртывайте без разрешения.'],['title'=>'Безопасность аккаунта','body'=>'Управляйте своим паролем и контактами. Защитите учётную запись администратора и никому не передавайте данные входа.'],
            ]],
            'tr' => ['title'=>'Liteback Yardım','intro'=>'Operatör konsolu için kısa rehber. Kaydetmeden önce önemli değişiklikleri onaylayın; bazı işlemler görünürlüğü, bakiyeleri veya hizmetleri etkiler.', 'sections'=>[
                ['title'=>'Kullanıcılar','body'=>'Oyuncu hesaplarını bulun, durumlarını inceleyin ve bakiye ayarlamalarını belgelendirin. Bir oyuncuyu değiştirmeden önce ayrıntıyı açın.'],['title'=>'Oyunlar','body'=>'Kataloğu, görünürlüğü, sağlayıcıları ve teslim ayarlarını yönetin. Geçmişi silmeden gizlemek için bir oyunu devre dışı bırakın.'],['title'=>'CEDAR','body'=>'Korumalı CEDAR kataloğunu ayrı yönetin. Yalnızca yetkili güncellemeleri senkronize edin; kimlikleri ve eski turları koruyun.'],['title'=>'Spor Bahisleri','body'=>'Spor alanını kontrol etmek için paneli, kategorileri, etkinlikleri, sonuçlandırmaları ve ayarları kullanın. Kaynak sonucu doğrulamadan sonuçlandırma veya iade yapmayın.'],['title'=>'Ödemeler ve çekimler','body'=>'Onaylamadan önce manuel yatırımları ve çekim taleplerini inceleyin. Gizli bilgileri notlara veya herkese açık alanlara asla yazmayın.'],['title'=>'Lotto Jackpot Bölgesi','body'=>'Çekilişleri oluşturun veya etkinleştirin, sonuç sütunlarını ayarlayın ve yalnızca hazır olduğunda belirli çekilişi çalıştırın. Sonuçlar denetlenir.'],['title'=>'Tahmin Piyasaları','body'=>'Piyasaları burada oluşturun ve inceleyin. Sonuçlandırma önemlidir: nihai sonucu doğrulayın ve belgelenen süreci izleyin.'],['title'=>'Kripto İşlemleri','body'=>'Lisanslı piyasa listesini yenileyin ve oyuncuların kullanabileceği varlıkları seçin. Pozisyonlar tarayıcı fiyatlarıyla değil kayıtlı anlık görüntülerle sonuçlanır.'],['title'=>'Hisse İşlemleri','body'=>'Hisse evrenini yenileyin ve varlıkları etkinleştirin veya devre dışı bırakın. Mevcut tur kanıtları korunur.'],['title'=>'Ortaklar ve yönlendirmeler','body'=>'Yönlendirme oranlarını ayarlayın ve programı inceleyin. Değişiklikler gelecekteki ödül hesaplarını etkiler.'],['title'=>'VIP ve rakeback','body'=>'VIP ayarlarını yapın ve izin verildiğinde oyuncu seviyesini değiştirin. Önce oyuncu kaydını daima kontrol edin.'],['title'=>'Sistem ve API ayarları','body'=>'Görünürlüğü, markayı, sağlayıcıları ve işletim ayarlarını kontrol edin. Bağlantıyı test edin ve en az bir giriş yöntemini etkin bırakın.'],['title'=>'Mağaza ve lisans','body'=>'Lisansı inceleyin, desteklenen indirmeleri isteyin ve onaylı güncellemeleri uygulayın. Yetki olmadan anahtar değiştirmeyin veya dağıtım yapmayın.'],['title'=>'Hesap güvenliği','body'=>'Kendi parolanızı ve iletişim bilgilerinizi yönetin. Yönetici hesabını koruyun ve giriş bilgilerini asla paylaşmayın.'],
            ]],
            'ar' => ['title'=>'مساعدة Liteback','intro'=>'دليل مختصر لوحدة تحكم المشغّل. أكّد التغييرات المهمة قبل الحفظ؛ فبعض الإجراءات تؤثر في الظهور أو الأرصدة أو الخدمات النشطة.', 'sections'=>[
                ['title'=>'المستخدمون','body'=>'ابحث عن حسابات اللاعبين وراجع حالتها ووثّق أي تعديل للرصيد. افتح التفاصيل قبل تغيير بيانات لاعب.'],['title'=>'الألعاب','body'=>'أدر الكتالوج والظهور والموفّرين وإعدادات التسليم. عطّل عنواناً لإخفائه من دون حذف السجل.'],['title'=>'CEDAR','body'=>'أدر كتالوج CEDAR المحمي بشكل منفصل. زامن التحديثات المصرّح بها فقط، وحافظ على المعرّفات والجولات السابقة.'],['title'=>'المراهنات الرياضية','body'=>'استخدم اللوحة والفئات والأحداث والتسويات والإعدادات للتحكم في قسم الرياضة. لا تسوِّ أو تردّ رهاناً قبل التحقق من النتيجة المصدرية.'],['title'=>'المدفوعات والسحوبات','body'=>'راجع الإيداعات اليدوية وطلبات السحب قبل الموافقة. لا تُدخل الأسرار مطلقاً في الملاحظات أو الحقول العامة.'],['title'=>'منطقة لوتو والجاكبوت','body'=>'أنشئ أو فعّل ألعاب السحب واضبط أعمدة النتيجة وشغّل سحباً محدداً فقط عندما يكون جاهزاً. تسجَّل النتائج للتدقيق.'],['title'=>'أسواق التوقعات','body'=>'أنشئ الأسواق وراجعها هنا. التسوية إجراء مهم: تحقّق من النتيجة النهائية واتبع العملية الموثقة.'],['title'=>'تداول العملات الرقمية','body'=>'حدّث قائمة السوق المرخّصة واختر الأصول المتاحة للاعبين. تستخدم المراكز لقطات مسجلة، لا أسعار المتصفح.'],['title'=>'تداول الأسهم','body'=>'حدّث قائمة الأسهم وفعّل الأصول أو عطّلها. تبقى أدلة الجولات الموجودة محفوظة عند تغيير الإتاحة.'],['title'=>'الشركاء والإحالات','body'=>'اضبط نسب الإحالة وراجع البرنامج. تؤثر التغييرات في حسابات المكافآت المستقبلية.'],['title'=>'VIP واسترداد الرهان','body'=>'اضبط إعدادات VIP، وعند السماح عدّل مستوى اللاعب. تحقّق دائماً من سجل اللاعب أولاً.'],['title'=>'إعدادات النظام وAPI','body'=>'تحكم في الظهور والعلامة التجارية والموفرين والإعدادات التشغيلية. اختبر الاتصال وأبقِ طريقة تسجيل دخول واحدة على الأقل مفعلة.'],['title'=>'المتجر والترخيص','body'=>'راجع حالة الترخيص واطلب التنزيلات المدعومة ونفّذ التحديثات المعتمدة. لا تستبدل المفاتيح أو تنشر تحديثات من دون تفويض.'],['title'=>'أمان الحساب','body'=>'استخدم هذه المنطقة لكلمة مرورك وبيانات الاتصال. احمِ حساب المسؤول ولا تشارك بيانات اعتماده مطلقاً.'],
            ]],
            'he' => ['title'=>'עזרה ב-Liteback','intro'=>'מדריך קצר לקונסולת המפעיל. אשרו שינויים חשובים לפני שמירה: פעולות מסוימות משפיעות על נראות, יתרות או שירותים פעילים.', 'sections'=>[
                ['title'=>'משתמשים','body'=>'אתרו חשבונות שחקנים, בדקו מצב ותעדו כל התאמת יתרה. פתחו את פרטי החשבון לפני שינוי שחקן.'],['title'=>'משחקים','body'=>'נהלו את הקטלוג, הנראות, הספקים וההגדרות. השביתו כותר כדי להסתירו בלי למחוק היסטוריה.'],['title'=>'CEDAR','body'=>'נהלו את קטלוג CEDAR המוגן בנפרד. סנכרנו רק עדכונים מורשים ושמרו על מזהים וסיבובים קודמים.'],['title'=>'הימורי ספורט','body'=>'השתמשו בלוח הבקרה, קטגוריות, אירועים, סליקות והגדרות. אל תסלקו או תחזירו הימור לפני אימות תוצאת המקור.'],['title'=>'תשלומים ומשיכות','body'=>'בדקו הפקדות ידניות ובקשות משיכה לפני אישור. לעולם אל תזינו סודות בהערות או בשדות ציבוריים.'],['title'=>'לוטו וג׳קפוט','body'=>'צרו או הפעילו הגרלות, הגדירו עמודות תוצאה והפעילו הגרלה מסוימת רק כשהיא מוכנה. התוצאות נשמרות לביקורת.'],['title'=>'שווקי תחזיות','body'=>'צרו ובדקו שווקים כאן. סליקה היא פעולה משמעותית: אמתו את התוצאה הסופית ופעלו לפי התהליך המתועד.'],['title'=>'מסחר בקריפטו','body'=>'רעננו את רשימת השוק המורשית ובחרו נכסים זמינים. הפוזיציות משתמשות בצילומי מצב שמורים ולא במחירי דפדפן.'],['title'=>'מסחר במניות','body'=>'רעננו את מאגר המניות והפעילו או השביתו נכסים. ראיות של סיבובים קיימים נשמרות בעת שינוי הזמינות.'],['title'=>'שותפים והפניות','body'=>'הגדירו שיעורי הפניה ובדקו את התוכנית. שינויים משפיעים על חישובי תגמול עתידיים.'],['title'=>'VIP ורייקבק','body'=>'הגדירו VIP, וכשמותר התאימו דרגת משתמש. בדקו תמיד את רשומת השחקן תחילה.'],['title'=>'הגדרות מערכת ו-API','body'=>'שלטו בנראות, במיתוג, בספקים ובהגדרות תפעוליות. בדקו חיבור והשאירו לפחות שיטת כניסה אחת פעילה.'],['title'=>'חנות ורישיון','body'=>'בדקו את הרישיון, בקשו הורדות נתמכות והחילו עדכונים מאושרים. אל תחליפו מפתחות או תפרסמו עדכונים ללא הרשאה.'],['title'=>'אבטחת חשבון','body'=>'השתמשו באזור זה לסיסמה ולפרטי הקשר שלכם. הגנו על חשבון המנהל ולעולם אל תשתפו אישורי כניסה.'],
            ]],
        ];
    }
}
