<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli' || count($argv) !== 3) { fwrite(STDERR, "Usage: php smoke_prepack.php prepack.zip practice-folder\n"); exit(2); }
require __DIR__ . '/../../casino/vendor/autoload.php';
use Symfony\Component\Process\Process;
$source = realpath(__DIR__ . '/../..');
$root = $source . '/.skills-backup/prepack-qa-' . gmdate('Ymd-His');
mkdir($root, 0700, true);
$zip = new ZipArchive(); if ($zip->open($argv[1]) !== true) throw new RuntimeException('Missing ZIP.'); $zip->extractTo($root); $zip->close();
$config = Dotenv\Dotenv::parse(file_get_contents($source . '/casino/.env'));
$db = 'promex_mvp_qa_' . bin2hex(random_bytes(5));
$pdo = new PDO('mysql:host=' . ($config['DB_HOST'] ?? '127.0.0.1') . ';port=' . ($config['DB_PORT'] ?? '3306'), $config['DB_USERNAME'], $config['DB_PASSWORD'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$pdo->exec('CREATE DATABASE `' . $db . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
$socket = stream_socket_server('tcp://127.0.0.1:0', $errno, $error); $address = stream_socket_get_name($socket, false); fclose($socket);
$server = new Process([PHP_BINARY, '-S', $address, '-t', $root], $root); $server->start();
$client = new GuzzleHttp\Client(['base_uri' => 'http://' . $address, 'cookies' => true, 'http_errors' => false, 'timeout' => 180]);
try {
    for ($i = 0; $i < 40; $i++) { try { $html = (string) $client->get('/install.php')->getBody(); break; } catch (Throwable) { usleep(100000); } }
    if (!preg_match('/name="installer_csrf" value="([^"]+)"/', $html ?? '', $csrf)) throw new RuntimeException('Installer form failed.');
    $response = $client->post('/install.php', ['form_params' => ['installer_csrf' => $csrf[1], 'db_host' => $config['DB_HOST'] ?? '127.0.0.1', 'db_port' => $config['DB_PORT'] ?? '3306', 'db_name' => $db, 'db_user' => $config['DB_USERNAME'], 'db_pass' => $config['DB_PASSWORD'], 'app_url' => 'http://casinoduliban.test', 'app_name' => 'MVP QA', 'license_key' => '']]);
    if (!is_file($root . '/installed.lock')) {
        file_put_contents($root . '/installer-result.html', (string) $response->getBody());
        throw new RuntimeException('Clean installer did not complete. Inspect private QA installer-result.html.');
    }
    echo "PASS: clean HTTP installer completed without license; forced password gate retained\n";
    $legacy = new Process([PHP_BINARY, $source . '/casino/tests/Updater/legacy-server-smoke.php', $root], $root . '/casino');
    $legacy->setTimeout(30)->run();
    if (!$legacy->isSuccessful() || !str_contains($legacy->getOutput(), 'balance_cash=') || !str_contains($legacy->getOutput(), 'reel_set')) {
        file_put_contents($root . '/legacy-server-result.txt', $legacy->getOutput() . $legacy->getErrorOutput());
        throw new RuntimeException('Packaged legacy doInit failed; inspect private QA legacy-server-result.txt.');
    }
    echo "PASS: packaged DayofDead server doInit returns game protocol (no wager)\n";
    $env = file_get_contents($root . '/casino/.env');
    $env = preg_replace('/^APP_ENV=.*$/m', 'APP_ENV=local', $env);
    $env .= "\nPROMEX_PATCH_DEMO=true\nPROMEX_PATCH_DEMO_PUBLIC_KEY_FILE=\"" . str_replace('\\', '/', realpath($argv[2]) . '/practice-public.pem') . "\"\n";
    file_put_contents($root . '/casino/.env', $env);
    $process = new Process([PHP_BINARY, $source . '/casino/tests/Updater/installed-flow.php', $root, realpath($argv[2])], $root . '/casino');
    $process->setTimeout(300)->run(); echo $process->getOutput();
    if (!$process->isSuccessful() || !str_contains($process->getOutput(), 'ALL INSTALLED FLOW CHECKS PASSED')) throw new RuntimeException('Installed flow failed: ' . $process->getErrorOutput());
    echo "PASS: extracted prepack functional smoke\n";
} finally {
    $server->stop();
    // Only the exact isolated database generated by this run is removed.
    if (preg_match('/^promex_mvp_qa_[a-f0-9]{10}$/D', $db)) $pdo->exec('DROP DATABASE `' . $db . '`');
    echo "Isolated QA files retained privately at {$root}; temporary QA database removed.\n";
}
