@extends('liteback.layout')
@section('title', 'Liteback - Loto Tur Kontrolü')
@section('content')
<div class="content-header"><div class="container-fluid"><h1 class="m-0 text-dark">🎯 Loto Tur Kontrolü</h1></div></div>
<section class="content"><div class="container-fluid">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row"><div class="col-lg-4"><div class="card card-primary"><div class="card-header"><h3 class="card-title">Loto Kuralı Oluştur</h3></div>
<form action="{{ route('liteback.lotto.store') }}" method="POST">@csrf <div class="card-body">
<div class="form-group"><label>Oyun adı</label><input name="title" class="form-control" required></div>
<div class="form-row"><div class="form-group col-6"><label>Numara havuzu</label><input type="number" name="max_number" class="form-control" value="49" min="10" max="99" required></div><div class="form-group col-6"><label>Seçimler</label><input type="number" name="pick_count" class="form-control" value="6" min="3" max="10" required></div></div>
<div class="form-row"><div class="form-group col-6"><label>Bilet ücreti</label><input type="number" name="entry_fee" class="form-control" value="500" min="0" required></div><div class="form-group col-6"><label>Jackpot</label><input type="number" name="jackpot_pool" class="form-control" value="250000" min="0" required></div></div>
<div class="form-row"><div class="form-group col-6"><label>Çekiliş sıklığı</label><select name="draw_interval" class="form-control"><option value="daily">Günlük</option><option value="hourly">Saatlik</option></select></div><div class="form-group col-6"><label>UTC saati</label><input name="draw_time" class="form-control" value="00:00" required><small class="text-muted">Günlük SS:DD; saatlik dakika.</small></div></div>
<div class="form-group"><label>Sonuç kaynağı</label><select name="draw_source" class="form-control"><option value="local">YEREL — burada üret</option><option value="promex_api">PROMEX API — lisanslı akış</option></select></div>
<label class="d-block">Genel sonuç sütunları</label>@foreach(['round_id'=>'Tur No','scheduled_for'=>'Day / time','numbers'=>'Winning numbers','my_tickets'=>'My ticket count','winners'=>'Winner count'] as $key=>$label)<div class="custom-control custom-checkbox"><input class="custom-control-input" type="checkbox" id="new_{{ $key }}" name="result_columns[]" value="{{ $key }}" checked><label class="custom-control-label" for="new_{{ $key }}">{{ $label }}</label></div>@endforeach
</div><div class="card-footer"><button class="btn btn-primary btn-block">Loto Oyunu Ekle</button></div></form></div></div>
<div class="col-lg-8"><div class="card card-dark"><div class="card-header"><h3 class="card-title">Oyunlar, program ve genel sonuçlar</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm table-striped mb-0"><thead><tr><th>Oyun</th><th>Kurallar</th><th>UTC programı</th><th>Kaynak</th><th>Tur sonuçlandırma</th><th>Durum</th></tr></thead><tbody>
@forelse($games as $g)<tr><td><strong>{{ $g->title }}</strong><br><small>{{ number_format($g->entry_fee,0) }} C ticket · {{ number_format($g->jackpot_pool,0) }} C pool</small></td><td>Pick {{ $g->pick_count }} / {{ $g->max_number }}</td><td>{{ ucfirst($g->draw_interval) }} · {{ $g->draw_time }} UTC</td><td><span class="badge badge-{{ $g->draw_source==='local'?'info':'warning' }}">{{ strtoupper($g->draw_source) }}</span></td><td><form action="{{ route('liteback.lotto.draw',$g) }}" method="POST" class="form-inline">@csrf<input name="round_id" class="form-control form-control-sm mr-1" placeholder="Çekiliş No / Tur No" required><button class="btn btn-sm btn-warning">Tetikleyici</button></form><small class="text-muted">Çekilmiş bir ID saklanan sonuçları döndürür.</small></td><td><form action="{{ route('liteback.lotto.toggle',$g) }}" method="POST">@csrf<button class="btn btn-xs {{ $g->is_active?'btn-outline-danger':'btn-outline-success' }}">{{ $g->is_active?'Disable':'Enable' }}</button></form></td></tr><tr class="bg-light"><td colspan="6"><form action="{{ route('liteback.lotto.result_columns',$g) }}" method="POST" class="form-inline">@csrf <strong class="mr-2">Oyuncu sonuçlarında göster:</strong>@foreach(['round_id'=>'Tur No','scheduled_for'=>'Day / time','numbers'=>'Numbers','my_tickets'=>'My tickets','winners'=>'Winners'] as $key=>$label)<label class="mr-2 font-weight-normal"><input type="checkbox" name="result_columns[]" value="{{ $key }}" {{ in_array($key,$g->result_columns_json ?: \VanguardLTE\Services\LottoDrawService::DEFAULT_RESULT_COLUMNS)?'checked':'' }}> {{ $label }}</label>@endforeach<button class="btn btn-xs btn-primary">Sütunları kaydet</button></form></td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-4">Tanımlı Loto Oyunu yok.</td></tr>@endforelse</tbody></table></div></div>
<div class="card card-info"><div class="card-header"><h3 class="card-title">Son turlar</h3></div><div class="card-body p-0 table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Tur No</th><th>Oyun</th><th>Planlanan UTC</th><th>Biletler</th><th>Kazananlar</th><th>Sonuç</th></tr></thead><tbody>@forelse($draws as $draw)<tr><td>{{ $draw->round_code ?: '#'.$draw->id }}</td><td>{{ $draw->game->title ?? 'Lotto' }}</td><td>{{ optional($draw->scheduled_for)->format('Y-m-d H:i') ?: $draw->draw_date }}</td><td>{{ $draw->total_tickets }}</td><td>{{ $draw->total_winners }}</td><td><span class="badge badge-{{ $draw->status==='drawn'?'success':'secondary' }}">{{ strtoupper($draw->status) }}</span> {{ $draw->status==='drawn'?implode(', ',$draw->winning_numbers_json ?: []):'' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Henüz tur yok.</td></tr>@endforelse</tbody></table></div></div></div></div>
</div></section>
@endsection
