@extends('frontend.Minimal.layouts.clean')
@section('page-title', 'Jackpot Bölgesi Loto')
@section('content')
<div class="space-y-5">
    <div><div class="inline-flex items-center gap-2 bg-primary/10 border border-primary/25 px-3 py-1 rounded-full"><span class="w-2 h-2 rounded-full bg-primary animate-pulse"></span><span class="text-[11px] font-bold text-primary font-mono-jet uppercase">Resmi planlı loto</span></div><h1 class="mt-2 text-2xl sm:text-3xl font-extrabold text-white uppercase">Jackpot Loto Bölgesi</h1><p class="text-on-surface-muted text-xs sm:text-sm">Her bilet, siz oynamadan önce görünür bir tura atanır.</p></div>
@if($currentGame)
    <div class="bg-[#121622] border border-white/[0.08] rounded-2xl overflow-hidden shadow-md">
        <div class="px-4 py-3 border-b border-white/[0.06] flex justify-between gap-3 text-xs"><span class="font-bold uppercase text-white">Bir oyun seçin</span><span class="font-mono-jet text-primary">{{ count($activeGames) }} active</span></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[660px] text-left text-xs"><thead class="text-on-surface-subtle uppercase font-mono-jet"><tr><th class="p-3">Oyun</th><th class="p-3">Kurallar</th><th class="p-3">Sonraki tur (UTC)</th><th class="p-3">Bilet</th><th class="p-3">Jackpot</th><th class="p-3"></th></tr></thead><tbody>
        @foreach($activeGames as $g) @php($selected=$g->id===$currentGame->id) <tr class="border-t border-white/[0.06] {{ $selected?'bg-primary/[0.08]':'' }}"><td class="p-3 font-bold text-white">{{ $g->title }}</td><td class="p-3">Pick {{ $g->pick_count }} / {{ $g->max_number }}</td><td class="p-3 text-accent-gold">{{ ucfirst($g->draw_interval) }} · {{ $g->draw_time }}<br><span class="text-on-surface-muted">{{ app(\VanguardLTE\Services\LottoDrawService::class)->nextScheduledFor($g,now('UTC'))->format('M d H:i') }}</span></td><td class="p-3 text-primary font-bold">{{ number_format($g->entry_fee,0) }} C</td><td class="p-3 text-accent-gold font-bold">{{ number_format($g->jackpot_pool,0) }} C</td><td class="p-3"><a href="?game={{ $g->slug }}" class="inline-flex px-3 py-1.5 rounded-lg font-bold {{ $selected?'bg-primary text-white':'bg-white/[0.06] text-on-surface-muted hover:text-white' }}">{{ $selected?'Selected':'Play' }}</a></td></tr> @endforeach
        </tbody></table></div>
    </div>
    <div class="bg-gradient-to-r from-[#161c2b] to-[#121622] rounded-2xl border border-primary/25 p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div class="text-[10px] text-primary font-mono-jet uppercase">Your ticket is for {{ $nextRound->round_code }}</div><div class="text-xl sm:text-2xl font-mono-jet font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-accent-gold to-yellow-300">{{ number_format($currentGame->jackpot_pool,0) }} CEDAR COINS</div></div><div class="text-xs font-mono-jet text-on-surface-muted">Çekilişler <strong class="text-white">{{ $nextRound->scheduled_for->format('D, M d · H:i') }} UTC</strong><br>Pick {{ $currentGame->pick_count }} numbers · {{ number_format($currentGame->entry_fee,0) }} C</div></div>
    <div class="bg-[#121622] rounded-2xl p-4 sm:p-5 border border-white/[0.08] space-y-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-sm font-bold text-white uppercase">Select your {{ $currentGame->pick_count }} numbers</h2><p class="text-xs text-on-surface-muted">Seçili bir numarayı kaldırmak için tekrar dokunun.</p></div><div id="selected-numbers" class="flex gap-1.5 min-h-8"></div><div class="flex items-center gap-2"><button id="btn-quick-draw" type="button" class="bg-accent-gold/15 hover:bg-accent-gold/25 border border-accent-gold/40 text-accent-gold px-3 py-2 rounded-xl text-xs font-extrabold uppercase">Hızlı Çekiliş</button><button id="btn-submit-ticket" disabled class="bg-primary hover:bg-primary-dark disabled:opacity-30 text-white px-4 py-2 rounded-xl text-xs font-extrabold uppercase">Play {{ number_format($currentGame->entry_fee,0) }} C</button></div></div>
        <div class="grid grid-cols-5 sm:grid-cols-8 md:grid-cols-10 gap-1.5">@for($i=1;$i<=$currentGame->max_number;$i++)<button type="button" data-num="{{ $i }}" class="num-btn py-2 rounded-lg bg-[#182030] border border-white/[0.06] font-mono-jet text-xs font-bold text-white hover:border-primary/60">{{ sprintf('%02d',$i) }}</button>@endfor</div>
    </div>
    <div class="bg-[#121622] rounded-2xl border border-white/[0.08] overflow-hidden"><div class="p-4 border-b border-white/[0.06] flex items-center justify-between"><h2 class="text-sm font-bold uppercase text-white">Son çekiliş sonuçları</h2><span class="text-xs font-mono-jet text-primary">{{ $currentGame->title }}</span></div><div class="overflow-x-auto"><table class="w-full min-w-[600px] text-xs"><thead class="text-on-surface-subtle uppercase font-mono-jet"><tr>@if(in_array('round_id',$resultColumns))<th class="p-3">Tur No</th>@endif @if(in_array('scheduled_for',$resultColumns))<th class="p-3">Gün / saat</th>@endif @if(in_array('numbers',$resultColumns))<th class="p-3">Numaralar</th>@endif @if(in_array('my_tickets',$resultColumns))<th class="p-3">Biletlerim</th>@endif @if(in_array('winners',$resultColumns))<th class="p-3">Kazananlar</th>@endif</tr></thead><tbody>@forelse($recentDraws as $draw)<tr class="border-t border-white/[0.06]">@if(in_array('round_id',$resultColumns))<td class="p-3 text-primary font-mono-jet">{{ $draw->round_code ?: '#'.$draw->id }}</td>@endif @if(in_array('scheduled_for',$resultColumns))<td class="p-3">{{ optional($draw->scheduled_for)->format('M d · H:i') ?: $draw->draw_date }} UTC</td>@endif @if(in_array('numbers',$resultColumns))<td class="p-3"><div class="flex gap-1">@foreach($draw->winning_numbers_json ?: [] as $number)<span class="w-6 h-6 rounded-full bg-primary/20 border border-primary/40 text-primary flex items-center justify-center font-bold">{{ $number }}</span>@endforeach</div></td>@endif @if(in_array('my_tickets',$resultColumns))<td class="p-3">@php($myTickets=$ticketsByDraw->get($draw->id,collect())) <strong class="text-white">{{ $myTickets->count() }}</strong> @foreach($myTickets as $ticket)<span class="ml-1 text-[10px] {{ in_array($ticket->status,['won','jackpot_win'])?'text-accent-gold':'text-on-surface-muted' }}">{{ strtoupper($ticket->status) }}</span>@endforeach</td>@endif @if(in_array('winners',$resultColumns))<td class="p-3 text-primary">{{ $draw->total_winners }}</td>@endif</tr>@empty<tr><td class="p-6 text-center text-on-surface-muted" colspan="5">Bu oyun için henüz çekilmiş tur yok.</td></tr>@endforelse</tbody></table></div></div>
@else <div class="bg-[#121622] p-8 rounded-2xl text-center text-on-surface-muted">Şu anda aktif bir loto oyunu yok.</div>@endif
</div>
@if($currentGame)<script>document.addEventListener('DOMContentLoaded',()=>{const count={{ $currentGame->pick_count }},max={{ $currentGame->max_number }},game={{ $currentGame->id }};let selected=[];const display=document.getElementById('selected-numbers'),submit=document.getElementById('btn-submit-ticket'),quickDraw=document.getElementById('btn-quick-draw'),buttons=document.querySelectorAll('.num-btn');const render=()=>{display.innerHTML=selected.map(n=>`<span class="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-mono-jet font-bold text-xs">${String(n).padStart(2,'0')}</span>`).join('')||'<span class="text-xs text-on-surface-subtle">0 / '+count+'</span>';buttons.forEach(b=>b.classList.toggle('bg-primary',selected.includes(+b.dataset.num)));submit.disabled=selected.length!==count};buttons.forEach(b=>b.onclick=()=>{let n=+b.dataset.num;selected=selected.includes(n)?selected.filter(x=>x!==n):(selected.length<count?[...selected,n].sort((a,b)=>a-b):selected);render()});quickDraw.onclick=()=>{selected=[];while(selected.length<count){const n=Math.floor(Math.random()*max)+1;if(!selected.includes(n))selected.push(n)}selected.sort((a,b)=>a-b);render()};submit.onclick=async()=>{submit.disabled=true;submit.textContent='Registering…';try{let r=await fetch('{{ route('frontend.lotto.play') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'},body:JSON.stringify({lotto_game_id:game,numbers:selected})}),d=await r.json();if(!d.success)throw Error(d.message);alert('Ticket '+d.ticket_id+' registered for '+d.round_id);location.reload()}catch(e){alert(e.message);submit.textContent='Play {{ number_format($currentGame->entry_fee,0) }} C';render()}};render()})</script>@endif
@endsection
